version: '3'
services:
  selenium:
    image: selenium/standalone-firefox-debug:3.141.59
    container_name: birdseyeapi_selenium
    ports:
      - 4444
    volumes:
      - /dev/shm:/dev/shm
    restart: always
  java:
    build: .
    container_name: birdseyeapi_java
    ports:
      - 8080
    tty: true
    volumes:
      - .:/project
    restart: always
    working_dir: /project
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
    env_file:
      - aws-credentials.env
  nginx:
    image: nginx:1.19.6
    container_name: birdseyeapi_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    restart: always
    tty: true
    ports:
      - 49999:49999