services:
  java:
    image: openjdk:22-bullseye
    container_name: birdseyeapi_java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/project
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    restart: always
    working_dir: /project
