version: "3"
services:
  java:
    build: .
    container_name: birdseyeapi_java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/project
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    restart: always
    working_dir: /project
    # root userでビルドするとroot所有のディレクトリが生成され、actions/checkoutでそれらのディレクトリ等が消せずにエラーになってしまう
    user: 1000:1000
